name: "Auto Tag"

on:
  push:
    branches:
      - '**'

permissions:
  contents: write

jobs:
  bump-and-tag:
    name: "Determine Next Version and Push Tag"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # fetch all history for tag detection

      - name: Bump version and create tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_prefix: ""  # numeric tags like 1.2.3

      - name: Output new tag
        run: echo "🚀 New tag created: ${{ steps.tag.outputs.new_tag }}"
