name: "Changelog Generation"

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  generate-changelog:
    name: "Generate or Update Changelog"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # fetch all history for changelog generation

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Conventional Changelog CLI
        run: npm install -g conventional-changelog-cli@latest

      - name: Generate Changelog
        id: changelog
        run: |
          # Generate or update CHANGELOG.md using angular preset
          if [ -f CHANGELOG.md ]; then
            conventional-changelog -p angular -i CHANGELOG.md -s
          else
            conventional-changelog -p angular -i CHANGELOG.md -s --release-count 0
          fi

      - name: Preview Changelog (PR only)
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "----- BEGIN CHANGELOG PREVIEW -----"
          cat CHANGELOG.md
          echo "------ END CHANGELOG PREVIEW ------"

      - name: Commit and Push Changelog (Push only)
        if: ${{ github.event_name == 'push' }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git diff --quiet || (
            git commit -m "docs: update changelog [skip ci]"
            git push origin HEAD:${{ github.ref_name }}
          )
