name: lint-scripts
on: [pull_request]

jobs:
  bashlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure script template header
        run: |
          for f in .github/scripts/*.sh; do
            grep -q "# Must support --test" "$f" || { echo "$f lacks required --test support"; exit 1; }
          done
