name: Release please
on:
  push:
    branches: [main, release/**]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GH_RELEASE_TOKEN }}
          release-type: simple
