name: UE build version
on:
  pull_request:
  push:
    branches: [main, release/**]
jobs:
  ue-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Project Version and Build Number
        uses: OrchidIsle/UE5-Semantic-Versioning@latest
        id: ver
        with:
          BUILD_PREFIX: dev
          CONFIG_DIR_PATH: ${{ github.workspace }}/MyGame/Config
          ADD_BUILD_INFO: true
          USE_RELEASE_BUILD: false
